# Generated by Django 5.2.1 on 2025-06-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signImg',
            field=models.ImageField(blank=True, null=True, upload_to='sign', verbose_name='Sign'),
        ),
    ]
